sonar.projectKey=utfprpb-oficina202502_laboratorio-dainf-client
sonar.organization=utfprpb-oficina202502
sonar.javascript.lcov.reportPaths=./coverage/lcov.info

# Exclude test files from analysis
sonar.exclusions=**/*.spec.ts,**/*.spec.js

# Exclude test files from coverage reporting
sonar.coverage.exclusions=**/*.spec.ts,**/*.spec.js,**/*.module.ts,**/testing/**,**/*.test-factory.ts

# Exclude test files from duplication detection
sonar.cpd.exclusions=**/*.spec.ts,**/*.spec.js,**/testing/**,**/*.test-factory.ts
